New blog: Small PVs and Kadalu Storage
kadalu/kadalu.github.io pull request #30
Opened 2020-02-04 18:09 UTC by aravindavk

Signed-off-by: Aravinda Vishwanathapura <mail@aravindavk.in>

2020-02-05 01:36 UTC, sankarshanmukhopadhyay requested changes

2020-02-05 01:36 UTC, sankarshanmukhopadhyay commented on _posts/2020-02-06-small-pvs-and-kadalu-storage.md
> +description: "Kadalu Storage can provide the smallest Persistent Volume as low as 20MiB for the applications running in Kubernetes(k8s). Small PVs are attractive for many use cases like providing hom
Should it be be Kadalu Storage can provide or, Kadalu Storage can provision?

2020-02-05 01:36 UTC, sankarshanmukhopadhyay commented on _posts/2020-02-06-small-pvs-and-kadalu-storage.md
> +What if Pod terminates abruptly or node goes down without calling Pre to stop hook script? Let's create a background job that syncs data from `$HOME` to `/srcdata` at regular intervals. For example,
What happens in cases where the Pod terminates abruptly or, the node goes down without being able to call Pre to stop the hook script?

2020-02-05 01:36 UTC, sankarshanmukhopadhyay commented on _posts/2020-02-06-small-pvs-and-kadalu-storage.md
> +**Note**: This approach is not suitable for large volumes, but a similar technique can be adapted for medium and large volumes if Inotify(or similar tools) is available for containers.
I think we should add a line to emphasize that this approach will still have data loss. The specific use case creates a trade off that losing data for such minimal time duration is considered to be acceptable.

2020-02-05 04:15 UTC, amarts approved these changes

2020-02-05 04:28 UTC, aravindavk commented
Do not merge now, we can plan to publish next week

2020-02-11 16:14 UTC, sankarshanmukhopadhyay approved these changes

2020-02-11 16:16 UTC, merged